- name: Actualizar imagen Frontend en EKS
        run: |
          kubectl set image deployment/tienda-frontend \
            frontend=${{ secrets.ECR_URL }}/tienda-frontend:${{ github.sha }} \
            -n tienda

      - name: Actualizar imagen Backend en EKS
        run: |
          kubectl set image deployment/tienda-backend \
            backend=${{ secrets.ECR_URL }}/tienda-backend:${{ github.sha }} \
            -n tienda
